name: Lint & Format Check

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install dependencies
        working-directory: cherrypick-fe
        run: npm ci

      - name: Run Linter
        working-directory: cherrypick-fe
        run: npm run lint

      - name: Check Formatting
        working-directory: cherrypick-fe
        run: npm run format
